### PR TITLE
Allow for new argument in Anki 2.1.45

### PR DESCRIPTION
**Pull request by AlexRiina**
In https://github.com/ankitects/anki/commit/49a1580566f403e445d186a4fbf4be1dcb4ff153
Anki gets a new argument for buttonTime. This PR supports both the old
and new argument types.

### CODE REVIEW

**Comment by s609078902** [comment]
seem that it still cannot run on anki 2.1.45

**Comment by s609078902** [comment]
Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 538, in handler
  File "C:\Users\shichuang\AppData\Roaming\Anki2\addons21\935264945\text.py", line 69, in <lambda>
    'getHtmlText()', lambda text: self.create(text, settings)
  File "C:\Users\shichuang\AppData\Roaming\Anki2\addons21\935264945\text.py", line 128, in create
    highlight = self._editExtract(newNote, did, settings)
  File "C:\Users\shichuang\AppData\Roaming\Anki2\addons21\935264945\text.py", line 157, in _editExtract
    addCards.deckChooser.setDeckName(deckName)
AttributeError: 'DeckChooser' object has no attribute 'setDeckName'

Can you fix this attribute error too? thank you so much.

**Comment by AlexRiina** [comment]
I'm no longer using this plugin for incremental reading, but it looks like instead of selecting the deck by name, the plugin may have to switch to selecting the deck by id via `deckchooser.selected_deck_id = did`

**Comment by tvhong** [comment]
Hi @AlexRiina,

Thank you for your contribution! I've made a similar (worse, actually) fix in https://github.com/luoliyan/incremental-reading/commit/4be88a5ad116ca9ce412f7989013167f7448db6c.

Since you mention that you no longer use this plugin for IR, I'll close this PR now. Appreciate your effort.

**Pull request closed without merging**
