### PR TITLE
2 kinds of defaults + remove outdated settings

### PR DESCRIPTION
**Pull request by TimotheeChauvin**
Changing the value of an item in self.defaults (e.g. changing the model name to 'IR4', or adding a bad tag) wouldn't be saved by people who already have the add-on installed: the values in _ir.json would take precedence.

### CODE REVIEW

**Comment by luoliyan** [comment]
That's intentional. If there is a setting that a user might want to change, my preference is to expose it in the UI, and have the add-on update `_ir.json`.

My plan was always to add a "Restore Defaults" button to the options dialog. This button will simply dump `settingsManager.defaults` to `_ir.json`. If the user is encouraged to mess around with the defaults, then the "Restore Defaults" function won't behave as expected.

If you give me a list of settings you think should be exposed, I'll take care of that.

**Comment by TimotheeChauvin** [comment]
I wasn't thinking about the user changing values, but about the developer: when you update the add-on with a new bad tag for example, the change is only going to be effective for people who don't have a `_ir.json` file, isn't it?

**Comment by luoliyan** [comment]
Oh dear, I hadn't thought about that.

In that case, I have a different idea:
* Embed the add-on version in `_ir.json` and check it on start-up
* Also flag each setting that has been modified by the user via the UI
* When a new version is installed, it overwrites any settings that were not changed by the user
* If the user wants everything overwritten, they click "Restore Defaults"

Sound reasonable?

**Comment by TimotheeChauvin** [comment]
This looks more flexible indeed. Can you do it in the next few days? Because I'm going to need this feature for the next pull request (and the last of this streak): the one about priorities. Otherwise I can do it myself.

**Comment by luoliyan** [comment]
I can probably finish it up tomorrow night.

**Comment by luoliyan** [comment]
Everything apart from "Restore Defaults" is done. I'll get to that one day...

**Pull request closed without merging**
